### ISSUE TITLE
Add `Create Class` to the `Management` Project

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#10]
There's a lot of heavy lifting in this issue before we can make templates.
- [x] Get the session key from the `Env` environment
- [x] Create the `Class #####` project
- [x] Create the `NoneKey`
- [x] Create the `NoneKeyLP`
- [x] Create the `playbook` repository from `rous`
- [x] Create the `vCenter` inventory
- [x] Create the blank `environment`

**Comment by uwardlaw** [comment]
There are a few approaches to this problem...

1) Create a playbook that uses `ansible.builtin.uri` and use Ansible to query the Semaphore API
2) Create a playbook that executes a python script on `Control` to query the Semaphore API
3) Create a playbook that executes a python script in the `Semaphore` container to query the Semaphore API

**Comment by uwardlaw** [comment]
Blocked by:
- #56

**Comment by uwardlaw** [comment]
`Create Class` was lagging, so I cancelled.

Error output:
```
3:41:05 PM Task 1 added to queue
3:41:09 PM Prepare task with template: Create Class
3:41:09 PM Cloning repository http://192.168.0.32:3000/333TRS/rous.git
3:41:09 PM Cloning into 'repository_1_1'...
3:41:09 PM No roles/requirements.yml file found. Skip galaxy install process.
3:43:20 PM Listing playbook hosts failed: exit status 4 [WARNING]: * Failed to parse /tmp/semaphore/repository_1_1/ansible/vm.vmware.yml with auto plugin: Unknown error while connecting to vCenter or ESXi API at 192.168.1.13:443 : [Errno 110] Operation timed out [WARNING]: * Failed to parse /tmp/semaphore/repository_1_1/ansible/vm.vmware.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory [WARNING]: * Failed to parse /tmp/semaphore/repository_1_1/ansible/vm.vmware.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port. [WARNING]: Unable to parse /tmp/semaphore/repository_1_1/ansible/vm.vmware.yml as an inventory source [WARNING]: No inventory was parsed, only implicit localhost is available [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' ERROR! 'uri' is not a valid attribute for a Play The error appears to be in '/tmp/semaphore/repository_1_1/ansible/createClassInSemaphore.yml': line 1, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: - name: Confirm Semaphore api is available ^ here
3:43:24 PM Preparing: 1
3:43:24 PM Prepare task with template: Create Class
3:43:24 PM Updating repository http://192.168.0.32:3000/333TRS/rous.git
3:43:24 PM hint: Pulling without specifying how to reconcile divergent branches is
3:43:24 PM hint: discouraged. You can squelch this message by running one of the following
3:43:24 PM hint: commands sometime before your next pull:
3:43:24 PM hint:
3:43:24 PM hint: git config pull.rebase false # merge (the default strategy)
3:43:24 PM hint: git config pull.rebase true # rebase
3:43:24 PM hint: git config pull.ff only # fast-forward only
3:43:24 PM hint:
3:43:24 PM hint: You can replace "git config" with "git config --global" to set a default
3:43:24 PM hint: preference for all repositories. You can also pass --rebase, --no-rebase,
3:43:24 PM hint: or --ff-only on the command line to override the configured default per
3:43:24 PM hint: invocation.
3:43:24 PM From http://192.168.0.32:3000/333TRS/rous
3:43:24 PM * branch master -> FETCH_HEAD
3:43:24 PM Already up to date.
3:43:24 PM No roles/requirements.yml file found. Skip galaxy install process.
```

I suspect the issue is that this is still using the `vmware` inventory file. The next action is probably to make a local only inventory for just this task template.

**Comment by uwardlaw** [comment]
Created a static `Localhost` Inventory file:

```
[localhost]
192.168.0.32
```

Eventually this will probably be an environment variable somewhere. `Localhost` is actually the `Control` and should be named that when I update the repo. 

Still throws the error:

```
7:37:26 PM PLAY [localhost] ***************************************************************
7:37:26 PM
7:37:26 PM TASK [Gathering Facts] *********************************************************
7:37:26 PM fatal: [192.168.0.32]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Host key verification failed.", "unreachable": true}
7:37:26 PM
7:37:26 PM
PLAY RECAP *********************************************************************
7:37:26 PM 192.168.0.32 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
7:37:26 PM Running playbook failed: exit status 4
```

**Comment by uwardlaw** [comment]
It's a little cumbersome, but we'll need to pass in extra variables for the playbooks with `["--extra-vars", "VARIABLE=VALUE"]`. For example, when creating a class, someone has to enter the class number. The ansible playbook expects the variable `class`. For the class `21012` one would enter `["--extra-vars", "class=21012"]` into  the  `Extra CLI arguments` dialogue box.

**Comment by uwardlaw** [comment]
Currently blocked. There are issues talking to `api/project/#/keys`.

`createClassInSemaphore.yml`
```yaml
  - name: Create key of type none
    uri:
      url: http://{{ controlIP }}:4000/api/project/{{ project.json.id }}/keys
      method: POST
      validate_certs: no
      return_content: yes
      headers:
        Content_Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ api_key }}"
      body_format: json
      body:
        name: "NoneKey"
        type: "none"
        project_id: "{{ project.json.id | int }}"
    register: noneKey

  - debug:
      var: noneKey
```

Errors with:

```
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "application/json", "date": "Wed, 03 Nov 2021 17:17:56 GMT", "elapsed": 0, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "status": 400, "url": "http://192.168.100.1:4000/api/project/20/keys"}
```

We can do it fine in Python.

`setupSemaphore.py`
```
214        # Create the key
215         print("---CREATING KEY OF TYPE NONE")
216         data = '{"name": "NoneKey", ' +                               \
217                '"type": "None", ' +                                   \
218                '"project_id": ' + str(managementProjectID) + '}'
219         response = s.post(url=host+api, headers=headers, data=data)
220         checkStatus(response)
```

Other attempts for `body` in the `createClassInSemaphore.yml` task `Create key of type none`.

```yaml
    body: "{\"name\":\"NoneKey\",\"type\":\"None\",\"project_id\":\" {{ project.json.id | int }} \"}"
```

Errors with:
```
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: An unknown error occurred: can't concat str to bytes", "redirected": false, "status": -1, "url": "http://192.168.100.1:4000/api/project/16/keys"}
```

When we use the `GET Method` for the same key that's setup in the `Management` project, we receive back:

```
"content": "[{\"id\":1,\"name\":\"NoneKey\",\"type\":\"None\",\"project_id\":1,\"removed\":false,\"login_password\":{\"login\":\"\",\"password\":\"\"},\"ssh\":{\"login\":\"\",\"passphrase\":\"\",\"private_key\":\"\"},\"override_secret\":false},{\"id\":2,\"name\":\"NoneKeyLP\",\"type\":\"login_password\",\"project_id\":1,\"removed\":false,\"login_password\":{\"login\":\"\",\"password\":\"\"},\"ssh\":{\"login\":\"\",\"passphrase\":\"\",\"private_key\":\"\"},\"override_secret\":false}]\n",
```

**Comment by uwardlaw** [comment]
Potential workaround:

- Create a Python script to create the `NoneKey` for us
- Parameters
  - `apiKey`: API key stored in the `Env` `Environment` for the `Authorization` piece of the header
  - `projectID`: ID for the project the key belongs to
  - `host`: The IP address for `Control`
- Copy it from `vater/control-services/bin/` to somewhere in the `Semaphore` image
- Run the script locally

**Comment by uwardlaw** [comment]
The `rous/ansible/createNoneKey.py` returns a `status_code 401`.
Output, inspecting the `session` object and the `response`.
```
control@control:~/rous/ansible$ python3 createNoneKey.py 6yeicxy2gtxzmqj1s1gbrdk92.168.100.1:40003ga= 2 http://19
key: 6yeicxy2gtxzmqj1s1gbrdk0riesdflee8mesdfq3ga=
{'adapters': OrderedDict([('https://',
                           <requests.adapters.HTTPAdapter object at 0x7f0c1e7df5e0>),
                          ('http://',
                           <requests.adapters.HTTPAdapter object at 0x7f0c1e7df640>)]),
 'auth': None,
 'cert': None,
 'cookies': <RequestsCookieJar[]>,
 'headers': {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Authorization': 'Bearer {sessionToken}'},
 'hooks': {'response': []},
 'max_redirects': 30,
 'params': {},
 'proxies': {},
 'stream': False,
 'trust_env': True,
 'verify': True}
{'_content': b'',
 '_content_consumed': True,
 '_next': None,
 'connection': <requests.adapters.HTTPAdapter object at 0x7f0c1e7df640>,
 'cookies': <RequestsCookieJar[]>,
 'elapsed': datetime.timedelta(microseconds=3348),
 'encoding': None,
 'headers': {'Content-Type': 'application/json', 'Date': 'Thu, 04 Nov 2021 13:21:53 GMT', 'Content-Length': '0'},
 'history': [],
 'raw': <urllib3.response.HTTPResponse object at 0x7f0c1e76b850>,
 'reason': 'Unauthorized',
 'request': <PreparedRequest [POST]>,
 'status_code': 401,
 'url': 'http://192.168.100.1:4000/api/project/2/keys'}
Operation returned non success status: 401
{'_content': b'',
 '_content_consumed': True,
 '_next': None,
 'connection': <requests.adapters.HTTPAdapter object at 0x7f0c1e7df640>,
 'cookies': <RequestsCookieJar[]>,
 'elapsed': datetime.timedelta(microseconds=3348),
 'encoding': None,
 'headers': {'Content-Type': 'application/json', 'Date': 'Thu, 04 Nov 2021 13:21:53 GMT', 'Content-Length': '0'},
 'history': [],
 'raw': <urllib3.response.HTTPResponse object at 0x7f0c1e76b850>,
 'reason': 'Unauthorized',
 'request': <PreparedRequest [POST]>,
 'status_code': 401,
 'url': 'http://192.168.100.1:4000/api/project/2/keys'}
```

**Comment by uwardlaw** [comment]
Reached success using the `createNoneKey.py` script.

Documenting other unsuccessful attempts and removing from `createClassInSemaphore.yml`

```yaml

# fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg":
# "Status code was -1 and not [200]: An unknown error occurred:
# can't concat str to bytes", "redirected": false, "status": -1,
# "url": "http://192.168.100.1:4000/api/project/16/keys"}

  - name: Create key of type none

    uri:
      url: http://{{ controlIP }}:4000/api/project/{{ project.json.id }}/keys
      method: POST
      validate_certs: no
      return_content: yes
      headers:
        Content_Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ api_key }}"
      body_format: json
      body: "{\"name\":\"NoneKey\",\"type\":\"None\",\"project_id\":\" {{ project.json.id | int }} \"}"
    register: noneKey

  - debug:
      var: noneKey

# Fails with bad request, status code 400

  - name: Create key of type none
    uri:
      url: http://{{ controlIP }}:4000/api/project/{{ project.json.id }}/keys
      method: POST
      validate_certs: no
      return_content: yes
      headers:
        Content_Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ api_key }}"
      body_format: raw
      body: {\\"name\":\\"NoneKey\\",\\"type\\":\\"None\\",\\"project_id\\":\\" {{ project.json.id | int }} \\"}
    register: noneKey

  - debug:
      var: noneKey
```
