### ISSUE TITLE
`vater restart -s jenkins` does not update the `casc.yaml`

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#146]
After `vater restart -s jenkins`:

```
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements for type class hudson.security.HudsonPrivateSecurityRealm : allowSignup.
Available attributes : allowsSignup, captchaSupport, enableCaptcha, users
```

Even though:

```
acontrol@control:~/vater/control-services/images/jenkins$ cat casc.yaml
authorization:
  globalMatrix:
    permissions:
    - Overall/Administer:adminOverall/Read:authenticated
jenkins:
  securityRealm:
    local:
      allowsSignup: 'false'
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://192.168.0.100/5000/
```
