### ISSUE TITLE
Add a task template to Create Class to create range

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#74]
Broken out from #10 which was incorrectly scoped / named.

This issue is purely about adding a task template to `Create Class`.

After a meeting, we decided the MVP for v0.1 needs to work towards the end design with `Jinja2`, but for now we can get away with much less. Updated #20, generated #77 and #76

- [x] Add `Create Range` template to `setupNewClass.py`
- [x] Setup SSH keys for Ansible to touch `Control`
- [x] Create `createRange.yml`
  - Iterates over `classSize`
  - Creates a workspace for each student
  - Destroys them at the end (for testing until `Destroy Range` is created)
- [x] Add test data about enclave VMs to `Group_vars` in `rous`
- [x] Add playbook task to grab project name
- [x] Add playbook task to execute Terraform `apply`
- [x] Test `createRange.yml` with a test `main.tf` in `rous`

**Comment by uwardlaw** [comment]
@marissaeinhorn Could use some help deciphering what should go in this playbook. Here's the Terraform module [documentation](https://docs.ansible.com/ansible/latest/collections/community/general/terraform_module.html).

If you tell me what commands you generally run to deploy an enclave, that would also be useful.

Along with information on what modules I should be paying attention to (maybe one of the examples fits good enough) a small test case from `rous` would be appreciated. I'd like to know expected output so I can confirm the playbook works.

**Comment by uwardlaw** [comment]
A few notes on how we can tackle this...

Found this in some RedHat [documentation](https://www.redhat.com/cms/managed-files/pa-terraform-and-ansible-overview-f14774wg-201811-en.pdf).

```yaml
---
- name: main
 hosts: all
 gather_facts: false
 connection: local
 tasks:
 - name: plan
 terraform:
 project_path: ‘terraform/’
 plan_file: “{{playbook_dir}}/tfplan”
 lock: true
 state: planned
 - name: apply
 terraform:
 project_path: ‘terraform/’
 lock: true
 state: present
 - name: destroy
 terraform:
 project_path: ‘terraform/’
 lock: true
 state: absent
```

**Comment by uwardlaw** [comment]
We should probably use Terraform `workspaces` to manage each separate range instance. This way the state files are separated and still managed by Terraform. [Documentation](https://www.terraform.io/docs/cli/workspaces/index.html).

There is a `workspace` parameter for Ansible `community.general.terraform`. If the different `inventory` files let Ansible know what hosts to manage and the `workspaces` let Terraform know what to manage, we just need to make sure Ansible tracks the name of the `workspace` to use it across different playbooks. There are a couple ways to handle this.

We should not add a list to the `environment`. We make the `environment` with the next class and don't change it after. This would stop us from making changes in the event someone drops out or something.

Instead we can make the `workspace` identifiable by `class#####` and `student##`.

**Comment by uwardlaw** [comment]
This [articles ](https://everythingshouldbevirtual.com/automation/generatingexecuting-terraform-plans-using-ansible/) has a great many hints and a great explanation for how we want to handle generation `terraform.tfvars` file with `jinja2`. The only reason we need one instead of using the same file for each `workspace` is because we want unique resource names in  vCenter.

**Comment by uwardlaw** [comment]
@marissaeinhorn I was wrong about my concerns with multiple `.tf` enclave files creating different Terraform `.tfstate` files. From the [documentation ](https://www.terraform.io/docs/language/index.html) on `Terraform Language`:

> The Terraform language is declarative, describing an intended goal rather than the steps to reach that goal. The ordering of blocks and the files they are organized into are generally not significant; Terraform only considers implicit and explicit relationships between resources when determining an order of operations.

Therefore we definitely should split the `.tf` files into enclaves.

**Comment by uwardlaw** [comment]
We can loop on `classSize` using the `range` and `loop` keywords referenced in the Ansible [documentation ](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html) on `Loops`.

```yaml
- name: with_sequence
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_sequence: start=0 end=4 stride=2 format=testuser%02x

- name: with_sequence -> loop
  ansible.builtin.debug:
    msg: "{{ 'testuser%02x' | format(item) }}"
  # range is exclusive of the end point
  loop: "{{ range(0, 4 + 1, 2)|list }}"
```
